In [1]:
import sys
import numpy as np
import pandas as pd
import seaborn as sns
from keras.models import Sequential
from sklearn.model_selection import KFold 
from keras.layers.core import Dense,Dropout
from sklearn.model_selection import RepeatedKFold
from sklearn.neighbors import KNeighborsClassifier
from keras.metrics import categorical_crossentropy

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest,chi2
from keras.layers import Activation,BatchNormalization
from keras.callbacks import ReduceLROnPlateau,EarlyStopping
from sklearn.preprocessing import RobustScaler,StandardScaler,LabelEncoder,MinMaxScaler
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.model_selection import train_test_split, cross_val_score,KFold,StratifiedKFold, GridSearchCV
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score,average_precision_score,recall_score,roc_auc_score

import matplotlib.pyplot as plt
from numpy.random import random
get_ipython().run_line_magic('matplotlib', 'inline')


In [2]:
import math
from sklearn import tree
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [26]:
from statistics import mean
import matplotlib.pyplot as plt
from sklearn.metrics import plot_roc_curve
pd.options.display.max_columns=None
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [4]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Dropout
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

In [5]:
Data = pd.read_csv("Phishing.csv",header="infer")

In [6]:
x=Data.iloc [:,1:-1]
x=x.values
y=Data.iloc[:,-1].values

In [7]:
dimension = Data.shape[1] - 1
print(dimension)

30


In [8]:
np.set_printoptions(threshold=sys.maxsize)
#print(y)

In [9]:
y = np.where(y >= 0, 1, -1)
#print(y)

# Evalution Function

In [10]:
def evaluation(clf, X, Y):
    print(f'Accuracy')
    acc = cross_val_score(clf, X, Y, scoring="accuracy", cv = 5)
    print(acc)
    print("Accuracy Score (Mean): ", acc.mean())
    print("Standard Error: ", acc.std())
    

    print(f'\nF1 Score')
    f1_score = cross_val_score(clf, X, Y, scoring="f1", cv = 5)
    print(f1_score)
    print("F1 Score (Mean): ", f1_score.mean())
    print("Standard Error: ", f1_score.std())
    
    print(f'\nPrecision')
    pre = cross_val_score(clf, X, Y, scoring="precision", cv = 5)
    print(pre)
    print("Precision (Mean): ", pre.mean())
    print("Standard Error: ", pre.std())
    
    print(f'\nSensitivity')
    rec = cross_val_score(clf, X, Y, scoring="recall", cv = 5)
    print(rec)
    print("Recall (Mean): ", rec.mean())
    print("Standard Error: ", rec.std())

# Train Test Split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=101)

# Decision tree

## Hyperparameter Tuning in Decision Trees

In [11]:
def hyperParameterTuning_DecisionTree(features, labels):
    params = {
        "max_features": ["auto", "sqrt", "log2"],
        "min_samples_leaf": [3, 4, 5],
        "min_samples_split": [8, 10, 12],
        "criterion": ["gini", "entropy"],
        "max_depth": [10, 20, 30, 40, 50],
        "random_state": [10, 20, 30, 40, 50]
    }
    
    rf_model = DecisionTreeClassifier()
    
    gsearch = GridSearchCV(estimator = rf_model, param_grid = params, cv = 5, n_jobs = -1, verbose = 1)
    
    gsearch.fit(features,labels)
    
    return gsearch.best_params_

In [12]:
hyperParameterTuning_DecisionTree(X_train, y_train)

Fitting 5 folds for each of 1350 candidates, totalling 6750 fits


{'criterion': 'entropy',
 'max_depth': 20,
 'max_features': 'auto',
 'min_samples_leaf': 3,
 'min_samples_split': 10,
 'random_state': 10}

In [12]:
clf_tree = DecisionTreeClassifier(criterion='entropy', max_depth=20, max_features='auto',
                                      min_samples_leaf = 3, min_samples_split = 10, random_state = 10)

In [13]:
evaluation(clf_tree, X_test, y_test)

Accuracy
[0.88788427 0.91500904 0.89511754 0.92224231 0.88768116]
Accuracy Score (Mean):  0.9015868647954506
Standard Error:  0.014351197887091667

F1 Score
[0.89935065 0.9248     0.90880503 0.93141946 0.89869281]
F1 Score (Mean):  0.9126135897979907
Standard Error:  0.01331441373818212

Precision
[0.90522876 0.91746032 0.88650307 0.91823899 0.90759076]
Precision (Mean):  0.9070043791803029
Standard Error:  0.01148341117924573

Sensitivity
[0.89354839 0.93225806 0.93225806 0.94498382 0.88996764]
Recall (Mean):  0.9186031944879423
Standard Error:  0.022434735494753753


# K-Nearest Neighbors

In [14]:
def hyperParameterTuning_KNN(features, labels):
    params = {
        "n_neighbors": [3, 5, 8, 10, 13],
        "weights": ["uniform", "distance"],
        "algorithm": ["auto", "ball_tree", "kd_tree"],
        "metric": ["minkowski", "euclidean", "manhattan"],
        "p": [1, 2, 3, 4, 5]
    }
    
    rf_model = KNeighborsClassifier()
    
    gsearch = GridSearchCV(estimator = rf_model, param_grid = params, cv = 5, n_jobs = -1, verbose = 1)
    
    gsearch.fit(features,labels)
    
    return gsearch.best_params_


In [19]:
hyperParameterTuning_KNN(X_train, y_train)

Fitting 5 folds for each of 450 candidates, totalling 2250 fits


{'algorithm': 'ball_tree',
 'metric': 'minkowski',
 'n_neighbors': 13,
 'p': 1,
 'weights': 'distance'}

In [15]:
clf_KNN = KNeighborsClassifier(algorithm = "ball_tree", metric = "minkowski", n_neighbors = 13, p = 1, weights = "distance")

In [16]:
evaluation(clf_KNN, X_test, y_test)

Accuracy
[0.94575045 0.94213382 0.92947559 0.93851718 0.93478261]
Accuracy Score (Mean):  0.9381319286107399
Standard Error:  0.00566313691534265

F1 Score
[0.95192308 0.94936709 0.93739968 0.94620253 0.94303797]
F1 Score (Mean):  0.9455860701664995
Standard Error:  0.005066430127968962

Precision
[0.94585987 0.93167702 0.93290735 0.92569659 0.92260062]
Precision (Mean):  0.9317482906220217
Standard Error:  0.00800984593958226

Sensitivity
[0.95806452 0.96774194 0.94193548 0.96763754 0.96440129]
Recall (Mean):  0.9599561540870655
Standard Error:  0.009671651471601895


# Random Forest  

In [17]:
def hyperParameterTuning_RF(features, labels):
    params = {
        "n_estimators": [30, 50, 70, 100],
        "criterion": ["gini", "entropy"],
        "max_depth": [10, 20, 30, 40, 50],
        "random_state": [10, 20, 30, 40, 50]
    }
    
    rf_model = RandomForestClassifier()
    
    gsearch = GridSearchCV(estimator = rf_model, param_grid = params, cv = 5, n_jobs = -1, verbose = 1)
    
    gsearch.fit(features,labels)
    
    return gsearch.best_params_

In [22]:
hyperParameterTuning_RF(X_train, y_train)

Fitting 5 folds for each of 200 candidates, totalling 1000 fits


{'criterion': 'entropy',
 'max_depth': 30,
 'n_estimators': 50,
 'random_state': 20}

In [18]:
clf_rf = RandomForestClassifier(criterion='entropy', max_depth=30, n_estimators=50, random_state=20)

In [19]:
evaluation(clf_rf, X_test, y_test)

Accuracy
[0.94755877 0.96202532 0.94394213 0.96202532 0.95471014]
Accuracy Score (Mean):  0.9540523363996121
Standard Error:  0.00737498651420638

F1 Score
[0.95389507 0.96618357 0.95008052 0.96629213 0.95987159]
F1 Score (Mean):  0.9592645771271593
Standard Error:  0.0064931678340952575

Precision
[0.94043887 0.96463023 0.94855305 0.95859873 0.9522293 ]
Precision (Mean):  0.9528900353387654
Standard Error:  0.00830299536991534

Sensitivity
[0.96774194 0.96774194 0.9516129  0.97411003 0.96763754]
Recall (Mean):  0.9657688694018164
Standard Error:  0.007499923852126231


# Support Vector Machine

In [20]:
def hyperParameterTuning_SVC(features, labels):
    params = {
        "kernel": ["linear", "poly", "rbf", "sigmoid"],
        "C": [1, 3, 5],
        "random_state": [10, 20, 30, 40, 50]
    }
    
    rf_model = SVC()
    
    gsearch = GridSearchCV(estimator = rf_model, param_grid = params, cv = 5, n_jobs = -1, verbose = 1)
    
    gsearch.fit(features,labels)
    
    return gsearch.best_params_

In [22]:
hyperParameterTuning_SVC(X_train, y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits


{'C': 5, 'kernel': 'rbf', 'random_state': 10}

In [23]:
clf_svm = SVC(random_state = 10, kernel = 'rbf', C = 5)

In [24]:
evaluation(clf_svm, X_test, y_test)

Accuracy
[0.93851718 0.93851718 0.93670886 0.93851718 0.94202899]
Accuracy Score (Mean):  0.9388578766674529
Standard Error:  0.001733345049333595

F1 Score
[0.94444444 0.94620253 0.94363929 0.94654088 0.9483871 ]
F1 Score (Mean):  0.9458428489665461
Standard Error:  0.0016673942203798838

Precision
[0.95695364 0.92857143 0.94212219 0.9204893  0.94533762]
Precision (Mean):  0.9386948349331151
Standard Error:  0.01283107454927292

Sensitivity
[0.93225806 0.96451613 0.94516129 0.97411003 0.95145631]
Recall (Mean):  0.9535003653826077
Standard Error:  0.014635976908925196


# Artificial Neural Network

In [27]:
def hyperParameterTuning_MLP(features, labels):
    params = {
        "hidden_layer_sizes": [(50,50,50), (50,100,50), (100,)],
        "activation": ['tanh', 'relu'],
        "max_iter": [500, 600, 800, 1000],
        "learning_rate": ['constant','adaptive', "invscaling"],
        "random_state": [10, 20, 30, 40, 50]
    }
    
    rf_model = MLPClassifier()
    
    gsearch = GridSearchCV(estimator = rf_model, param_grid = params, cv = 5, n_jobs = -1, verbose = 1)
    
    gsearch.fit(features,labels)
    
    return gsearch.best_params_

In [28]:
hyperParameterTuning_MLP(X_train, y_train)

Fitting 5 folds for each of 360 candidates, totalling 1800 fits


{'activation': 'tanh',
 'hidden_layer_sizes': (100,),
 'learning_rate': 'constant',
 'max_iter': 500,
 'random_state': 20}

In [29]:
clf_mlp = MLPClassifier(activation = "tanh", hidden_layer_sizes = (100, ), learning_rate = "constant", 
                         max_iter = 500, random_state = 20) 

In [ ]:
evaluation(clf_mlp, X_test, y_test)

Accuracy


C:\Users\SAFIAL ISLAM AYON\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\SAFIAL ISLAM AYON\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\SAFIAL ISLAM AYON\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.93309222 0.94213382 0.93490054 0.9403255  0.93478261]
Accuracy Score (Mean):  0.9370469376523312
Standard Error:  0.0035213416783245943

F1 Score


C:\Users\SAFIAL ISLAM AYON\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\SAFIAL ISLAM AYON\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\SAFIAL ISLAM AYON\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.93944354 0.94855305 0.94230769 0.94753577 0.94193548]
F1 Score (Mean):  0.9439551074188877
Standard Error:  0.003495980858594808

Precision


C:\Users\SAFIAL ISLAM AYON\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\SAFIAL ISLAM AYON\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


# ROC Curve

In [ ]:
def roc_curve_normal(X, Y):
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25)
    
    clf_tree = DecisionTreeClassifier(criterion='entropy', max_depth=20, max_features='auto',
                                      min_samples_leaf = 3, min_samples_split = 10, random_state = 10)
    clf_tree.fit(X_train, y_train)
    #Curve Point
    #y_score1 = clf_random.predict_proba(X_test)[:,1]
    #false_positive_rate1, true_positive_rate1, threshold1 = roc_curve(y_test, y_score1)
    #print(false_positive_rate1, true_positive_rate1, threshold1)
    
    #X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25)
    clf_KNN = KNeighborsClassifier(algorithm = "ball_tree", metric = "minkowski", n_neighbors = 13, p = 1, weights = "distance")
    clf_KNN.fit(X_train, y_train)
    
    clf_rf = RandomForestClassifier(criterion='entropy', max_depth=30, n_estimators=50, random_state=20)
    clf_rf.fit(X_train, y_train)
    
    clf_svm = SVC(random_state = 10, kernel = 'rbf', C = 5)
    clf_svm.fit(X_train, y_train)
    
    clf_mlp = MLPClassifier(activation = "tanh", hidden_layer_sizes = (50, 100, 50), learning_rate = "constant", 
                         max_iter = 500, random_state = 30) 
    clf_mlp.fit(X_train, y_train)
    
    
    ax = plt.gca()
    
    clf_tree_disp = plot_roc_curve(clf_tree, X_test, y_test, ax=ax, alpha=0.8)
    clf_KNN_disp  = plot_roc_curve(clf_KNN, X_test, y_test, ax=ax, alpha=0.8)
    clf_rf_disp   = plot_roc_curve(clf_rf, X_test, y_test, ax=ax, alpha=0.8)
    clf_svm_disp  = plot_roc_curve(clf_svm, X_test, y_test, ax=ax, alpha=0.8)
    clf_mlp_disp  = plot_roc_curve(clf_mlp, X_test, y_test, ax=ax, alpha=0.8)
    
    ax.figure.set_size_inches(20, 12)
    plt.show()

In [ ]:
roc_curve_normal(x, y) 